export default {
  actions: {
    loading: 'Loading',
  },
  network: {
    connectionError: 'Connection error',
  },
  home: {
    header: 'Home',
    message: 'Welcome',
    explore: 'Explore',
    empty: 'There are no items yet, come back later',
  },
  login: {
    email: 'Email',
    emailHint: 'Enter your email',
    button: 'Login',
    password: 'Password',
    passwordHint: 'Enter your password',
    invalidCredentials: 'Invalid Email/Password',
    register: 'Do not have an account? Sign up',
  },
  register: {
    name: 'Name',
    nameHint: 'Enter your name',
    email: 'Email',
    emailHint: 'Enter your email',
    button: 'Register',
    password: 'Password',
    passwordHint: 'Enter your password',
    passwordCheck: 'Password',
    passwordCheckHint: 'Enter your password',
    invalidCredentials: 'Invalid Email/Password',
    login: 'Already have an account? Log in',
  },
  profile: {
    header: 'Profile',
    logout: 'Logout',
    myItems: 'View My items',
  },
  items: {
    sendMessage: 'Contact',
    owner: 'Posted by:',
    distance: 'Distance: ',
    unit: 'meter(s)',
  },
  createMessage: {
    header: 'Send Message',
    body: 'Message',
    bodyHint: 'Enter the message you wish to send the owner to coordinate pickup',
    button: 'Send',
    invalidMessage: 'Invalid message',
  },
  createItem: {
    header: 'Add Item',
    title: 'Title',
    titleHint: 'Enter the title of the item',
    description: 'Description',
    descriptionHint: 'Enter the description of the item',
    image: 'Image',
    cameraButton: 'Camera',
    galleryButton: 'Gallery',
    latitude: 'Latitude',
    latitudeHint: 'Enter the latitude (between -90 and 90)',
    longitude: 'Longitude',
    longitudeHint: 'Enter the longitude (between -180 and 180)',
    locationDetails: 'Location details',
    locationDetailsHint: 'Enter the details of the location of the item',
    button: 'Add',
    invalidItem: 'Invalid item',
  },
  messages: {
    header: 'My inbox',
    from: 'From: ',
    empty: 'Your inbox is empty',
  },
  myItems: {
    empty: 'You currently have no items, start by adding some!',
  }
};
